# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: raja app

on:
  workflow_dispatch:
    inputs:
      src_job_id:
        description: "Enter Databricks job ID from source"
        required: true
        default: "Sample Text"
      job_opration:
        description: "Choose an option to go ahead"
        required: true
        default: "Option1"
        type: choice
        options:
          - INSERT
          - UPDATE
          - DELETE

jobs:
  user-input-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Inputs
        run: |
          echo "Text Input: ${{ github.event.inputs.text_input }}"
          echo "Option Input: ${{ github.event.inputs.option_input }}"

      - name: Check Inputs
        run: |
          if [[ "${{ github.event.inputs.text_input }}" == "success" && "${{ github.event.inputs.option_input }}" == "Option1" ]]; then
            echo "Workflow Success"
          else
            echo "Workflow Failure"
          fi
